package com.app.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_name
     *
     * @mbggenerated
     */
    private String atuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_email
     *
     * @mbggenerated
     */
    private String atuEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_uid
     *
     * @mbggenerated
     */
    private String atuUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_pwd
     *
     * @mbggenerated
     */
    private String atuPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_status
     *
     * @mbggenerated
     */
    private Integer atuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_purview
     *
     * @mbggenerated
     */
    private Integer atuPurview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_createtime
     *
     * @mbggenerated
     */
    private Date atuCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column at_users.atu_updatetime
     *
     * @mbggenerated
     */
    private Date atuUpdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.id
     *
     * @return the value of at_users.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.id
     *
     * @param id the value for at_users.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_name
     *
     * @return the value of at_users.atu_name
     *
     * @mbggenerated
     */
    public String getAtuName() {
        return atuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_name
     *
     * @param atuName the value for at_users.atu_name
     *
     * @mbggenerated
     */
    public void setAtuName(String atuName) {
        this.atuName = atuName == null ? null : atuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_email
     *
     * @return the value of at_users.atu_email
     *
     * @mbggenerated
     */
    public String getAtuEmail() {
        return atuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_email
     *
     * @param atuEmail the value for at_users.atu_email
     *
     * @mbggenerated
     */
    public void setAtuEmail(String atuEmail) {
        this.atuEmail = atuEmail == null ? null : atuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_uid
     *
     * @return the value of at_users.atu_uid
     *
     * @mbggenerated
     */
    public String getAtuUid() {
        return atuUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_uid
     *
     * @param atuUid the value for at_users.atu_uid
     *
     * @mbggenerated
     */
    public void setAtuUid(String atuUid) {
        this.atuUid = atuUid == null ? null : atuUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_pwd
     *
     * @return the value of at_users.atu_pwd
     *
     * @mbggenerated
     */
    public String getAtuPwd() {
        return atuPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_pwd
     *
     * @param atuPwd the value for at_users.atu_pwd
     *
     * @mbggenerated
     */
    public void setAtuPwd(String atuPwd) {
        this.atuPwd = atuPwd == null ? null : atuPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_status
     *
     * @return the value of at_users.atu_status
     *
     * @mbggenerated
     */
    public Integer getAtuStatus() {
        return atuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_status
     *
     * @param atuStatus the value for at_users.atu_status
     *
     * @mbggenerated
     */
    public void setAtuStatus(Integer atuStatus) {
        this.atuStatus = atuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_purview
     *
     * @return the value of at_users.atu_purview
     *
     * @mbggenerated
     */
    public Integer getAtuPurview() {
        return atuPurview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_purview
     *
     * @param atuPurview the value for at_users.atu_purview
     *
     * @mbggenerated
     */
    public void setAtuPurview(Integer atuPurview) {
        this.atuPurview = atuPurview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_createtime
     *
     * @return the value of at_users.atu_createtime
     *
     * @mbggenerated
     */
    public Date getAtuCreatetime() {
        return atuCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_createtime
     *
     * @param atuCreatetime the value for at_users.atu_createtime
     *
     * @mbggenerated
     */
    public void setAtuCreatetime(Date atuCreatetime) {
        this.atuCreatetime = atuCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column at_users.atu_updatetime
     *
     * @return the value of at_users.atu_updatetime
     *
     * @mbggenerated
     */
    public Date getAtuUpdatetime() {
        return atuUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column at_users.atu_updatetime
     *
     * @param atuUpdatetime the value for at_users.atu_updatetime
     *
     * @mbggenerated
     */
    public void setAtuUpdatetime(Date atuUpdatetime) {
        this.atuUpdatetime = atuUpdatetime;
    }
}